id: A9FD5546A
title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously Fulfills
  All Wishes (Sampa Lhundrupma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:59:52.032932
  last_modified_at: 2022-03-01 01:59:52.032936
