id: A9FD5546A
title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:59:52.019788
  last_modified_at: 2022-03-01 01:59:52.019796
