id: A9FD5546A
title: The Means for Accomplishment called the Blazing Wheel
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:59:52.034539
  last_modified_at: 2022-03-01 01:59:52.034542
